## --- Metadata Options --- ##

# [string] @title       : Name of the game, default: 'SuperGame'.
# [string] @author      : Author of the game, default: 'SuperAuthor'
# [string] @description : Description of the game, default: 'SuperDescription'
# [string] @version     : Version of the game in {major}.{minor}.{revision} format, default: '0.1.0'
# [string] @icons       : Icon paths, defaults: empty string ('')
[metadata]
title = "LoveVNEngine"
author = "wewewer123"
description = "a random love vn engine"
version = "2.0.0"
icons = { ctr = "", hac = "", cafe = "" }

## --- Build Options --- ##

# [array]  @targts        : Target console(s) to build for. Default: ["ctr", "hac", "cafe"].
#
# [string] @source        : Game source directory; relative to the config
#                           file. Default: "game".
# [int]    @app_version   : Version of LÖVE Potion to build for. Default: 2
[build]
targets = ["ctr", "hac", "cafe"]
source = "game"
packaged = true

[debug]
version = "0.10.0"