Name = "Sam"; NameChangable = true; ScriptContainer = 
{
	"Name .name. Okay. The pumpkin’s a good start.",
	"I instinctively look at the clock. Normally time to get ready for a party.",
	"I wonder if I’m getting done soon enough. Otherwise I’d need to stay. Alone.",
	"Moving here was a good idea. Although the timing was… questionable.",
	"I barely had time to sort out my stuff. Why did I move a day before Halloween?",
	"At least I have the necessities right now, even if it’s a bit chaotic. Now I can prepare for the holi–",
	"Knock knock",
	"Hmm. Someone’s at the door. Shouldn’t they all be busy preparing their Halloween stuff?",
	"What should I do? Open the door or Ignore the knock and open a box?", ---------- add touch system: box 100 ----------",
	"I open the door. I’m greeted by a person in a way too big orange sweater beaming at me.",
	"? .name. Hello! The name’s Raven. I’m your neighbour. Here’s a welcoming gift!",
	"With those words they push a basket into my arms. It’s filled with different biscuits.",
	"Raven .name. Didn’t know what you liked, so I just packed it.",
	"Name .name. Thanks…",
	"They seem extremely enthusiastic. Back in town, people were mostly annoyed about a new face disrupting their routines…",
	"As I examine the rather good looking sweets in the basket, I catch Raven trying to take a look into my house.",
	"They notice my glance and scratch their ear, blushing.",
	"Raven .name. Sorry. I’m just curious. Seems like you’re still unpacking. I didn’t interrupt you, did I?",
	"To be fair, I welcome the distraction right now. Decorating and unpacking isn’t the most pleasant pastime.",
	"I still hold their basket. Maybe I should invite them in? It’d be basic courtesy, after all. And I can’t eat all those (very good smelling) biscuits alone.",
	"Although that would certainly make any plans for a party impossible. qqq 117 yyy Invite them in. nnn Give the basket back.",
	"Name .name. You’d like to come in? Then you don’t have to look past me.",
	"Raven .name. I’d like to, thanks. Only if it’s no bother though.",
	"Name .name. None at all.",
	"I step aside, so Raven can enter my room. As I close the door, they already check out the bookshelf.",
	"I place the basket on the table and offer them a seat.",
	"Name .name. Can I offer you something?",
	"They sit down while still scanning my room. It feels like they get a read on my whole personality.",
	"Raven .name. A tea would be nice. I drink everything.",
	"They laugh and continue to look around the room.",
	"Name .name. Tea it is then.",
	"It certainly fits the biscuits. So, time to make tea.",
	"Luckily, I don’t have that many different teas.",
	"But which one should I take? qqq 138 yyy Camomile. nnn Black Tea.",
	"I set up the pot. Raven stares at all my books, lost in thought.",
	"Name .name. See anything you like?",
	"Raven .name. Happy to see a bookshelf! The red one on the top shelf above the fireplace looks interesting!",
	"They look fascinated. I think they would love to get lost in those books. No harm ever came from reading a book, right?",
	"Name .name. You want to check one out?",
	"Ravens eyes light up as they look at me.",
	"Raven .name. Can I? I don’t want to mess anything up!",
	"Name .name. No problem. I’ll get it for you.",
	"So, which one was it again? Click on the right book.", ---------- add touch system: wrong book 132 ----------",
	"I hand Raven the book, they immediately start to flip through it and seem to lose themself in it.",
	"The tea pot whizzes. While I pour the tea for us two, they close the book.",
	"Raven .name. Looks good. Maybe I can borrow it someday?",
	"They smile.",
	"Raven takes one of the cups I bring to them and clears the stool so I can sit down too.",
	"Raven .name. Smells good. Now for the taste…",
	"They take a sip. Their face lightens up. I take a sip too. It tastes really well.",
	"Raven .name. Hmm, my favourite. Just the right thing to relax after a busy day.",
	"Name .name. Had plans. But now I think this was the better choice.",
	"Raven .name. Can’t argue with that.",
	"I remember the biscuits and as I take one, their hand follows.",
	"They fit perfectly to the tea. Almost like they were picked deliberately.",
	"They start to talk a bit about themself, then asks me why I moved here.",
	"I start to talk. I wanted to move away from the buzzing and stressful town and start anew.",
	"Raven .name. You picked a great place for that.",
	"Name .name. I agree. Although I’m still busy with moving in. And the holiday troubles.",
	"Raven .name. Yeah, I see. You look a little bit stressed.",
	"We both take a sip of tea. I enjoy the silence while they start to look around again.",
	"Maybe I can just tell them about stuff they seem interested in.",
	"Raven looks at: the boxes, the bottle, the painting or the lamp.", ---------- add touch system bottle 162, painting 170, lamp 181----------",
	"Ravens eyes dart to the decoration boxes. Their facial expressions betray the question before it is asked.",
	"Name .name. It’s the halloween decorations. I was starting to work on it before you knocked.",
	"Raven .name.  Oh.",
	"Their look drifts around the room and stops at the pumpkin.",
	"Raven .name. I like the pumpkin.",
	"Name .name. ...Thanks.",
	"They look at me for a second, thinking, before they ask a question I’ll never forget.",
	"Raven .name. Why?",
	"Name .name. Why what?",
	"Raven .name. Why decorate more?",
	"Name .name. I… Well…",
	"That’s a very good question. Why? qqq 135 yyy Oh, you know… Party and stuff. nnn Oh, ehh, well…",
	"Raven chuckles.",
	"Raven .name. You’re always that busy on halloween?",
	"They take a sip of their tea and close their eyes for a moment as they hold the cup with both hands.",
	"I say nothing, and just enjoy the moment. It’s quiet. Peaceful.",
	"It’s wonderful.",
	"Raven .name. I do think we can make it a bit better without all the decorating work.",
	"As they speak, they put the cup on the table, stand up and walk towards the fireplace.",
	"Raven .name. That would be much better!",
	"Raven looks expectantly at me. I go up to them and together we put some wood in the fireplace to start the fire.",
	"Raven .name. Almost perfect.",
	"We both turn towards the pumpkin.",
	"I grab a candle I bought for the decorations.",
	"Raven gives me their lighter.",
	"They watch as I place the candle in the pumpkin and light it up.",
	"The light and shadows dance through the room as I turn off the light.",
	"I see their eyes, illuminated by the flame of the fireplace.",
	"I never saw someone so purely happy.",
	"They grab their cup and sit down on a chair.",
	"I follow and sit down beside them.",
	"For the first time in an eternity, I feel content. Happy.",
	"Raven smiles at me, toasting with their cup.",
	"Raven .name. By the way… thanks for the tea.",
	"123quit123",
	"",
	"I shrug and start to open the box, hoping that maybe they aren’t persistent.",
	"...Knock Knock Knock",
	"? .name. Hello? Can I talk to you for just a moment, please?",
	"The voice is gentle, yet firm. I have a feeling it has enough patience to wait through the whole night.",
	"The thought of letting someone stand outside at the end of October feels… wrong.",
	"What now? continue just working on the decorations, or let the person in?", ---------- add touch system: Decoration 109 ----------",
	" ggg 10",
	"",
	"",
	"I ignore the knocking. I’ve got stuff to do. Places to be.",
	"? .name. I know you’re here. It’s bad form, ignoring neighbours here, you know that?",
	"It starts to dawn on me that handling a situation that poorly does reflect badly on me. First impression and all that.",
	"With a sigh, I go to open the door.",
	"I open the door. I’m greeted by a person in a way too big orange sweater beaming at me.",
	"They shiver slightly, as it is rather cold.",
	" ggg 11",
	"",
	"I can’t just drop my plans. I have to get stuff done.",
	"I give the basket back. Raven looks disappointed, but takes it back nonetheless.",
	"Raven .name. I guess you don’t like biscuits?",
	"Name .name. No, it’s just… I have stuff to do, y’know. Need to get going!",
	"Raven .name. Oh. I understand. You’re busy, always on the move. Maybe another time then!",
	"Name .name. Maybe.",
	"As I close the door, I check the time again. It’s pretty late. I still need to do much.",
	"After a few hours, I’m finally ready to hurry out. It’s going to be a stressful Halloween getting to the party in time.",
	"Stress seems to follow me wherever I go.",
	"Name .name. Costume? Check. Phone? Check. Wallet? Check. Keys? … Oh, where are my keys?!",
	"It won’t get any better tonight, I guess…",
	"I can’t shake the feeling I might have made a mistake…",
	"123quit123",
	"",
	"",
	"No, not that one!",
	" ggg 43",
	"",
	"Raven .name. Gotcha.",
	" ggg 78",
	"",
	"I set up the pot. Raven stares at all my books, lost in thought.",
	"Name .name. See anything you like?",
	"Raven .name. Happy to see a bookshelf! The red one on the top shelf above the fireplace looks interesting!",
	"They look fascinated. I think they would love to get lost in those books. No harm ever came from reading a book, right?",
	"Name .name. You want to check one out?",
	"Ravens eyes light up as they look at me.",
	"Raven .name. Can I? I don’t want to mess anything up!",
	"Name .name. No problem. I’ll get it for you.",
	"So, which one was it again? Click on the right book.", ---------- add touch system: wrong book 159 ----------",
	"I hand Raven the book, they immediately start to flip through it and seem to lose themself in it.",
	"The tea pot whizzes. While I pour the tea for us two, they close the book.",
	"Raven .name. Looks good. Maybe I can borrow it someday?",
	"They smile.",
	"Raven takes one of the cups I bring to them, and clears the stool so I can sit down too.",
	"Raven .name. Smells good. Now for the taste…",
	"Raven .name. Interesting choice. A bit hectic for a relaxing evening. A real city choice. Still good!",
	"Name .name. Well. I planned to go to a party. An energy boost would have been helpful.",
	"They laugh.",
	"Raven .name. My apologies for ruining your plans.",
	" ggg 54",
	"",
	"No, not that one!",
	" ggg 146",
	"",
	"Their gaze catches the bottles. Raven raises an eyebrow slightly. Damn beer.",
	"Raven .name. You already had a visitor?",
	"Name .name. ...No. Took a break from unloading my stuff.",
	"Ravens looks at me. I can’t figure out their expression. Concern? Amusement? Pity?",
	"Name .name. I know, it’s not healthy…",
	"I really should stop drinking.",
	" ggg 63",
	"",
	"Raven tilts their head as they examine the painting on my wall.",
	"Raven .name. It’s pretty. Where’d you get it?",
	"Name .name. I painted it. It’s one of my favourite hobbies.",
	"It’s true. One of the reasons I moved here was to find beautiful places to put on a frame.",
	"Raven .name. Really?! It’s such a great painting! I’m impressed. You’ll find lots of picturesque places here!",
	"A grin starts to sneak on their face.",
	"Raven .name. Maybe even a portrait of me? I always wanted to be drawn!",
	"They laugh and it’s infectious. I have no choice but to join in.",
	"Name .name. Thank you. Maybe I could draw a portrait someday.",
	" ggg 63",
	"",
	"Raven takes a quick look at the lamp.",
	"Raven .name. Looks… interesting. Although a bit unfitting…",
	"Name .name. I’ve had it for a while. A dear friend bought it for me.",
	"Raven .name. Ah, sentimental value. I understand.",
	"Name .name. It’s not the prettiest lamp. But it’s a memory I wanted to keep. Remember some good times, you know?",
	"Ravens' glance is warm and intense as they listen to my words.",
	"Raven .name. Yes… Sorry. I should not judge a book by its cover. Beauty’s on the inside.",
	"They go silent for a few moments, lost in thought, before they clap their hands and smile.",
	"Raven .name. Enough philosophical pondering!",
	"Raven starts to look around again.",
	" ggg 63",
	
}
return { ScriptContainer, Name, NameChangable }