ScriptContainer = 
{
    "It's only when I hear the sounds of shuffling feet and supplies being put away that I realize that the lecture's over.",
    "Professor Eileen's lectures are usually interesting, but today I just couldn't concentrate on it.",
    "I've had a lot of other thoughts on my mind...thoughts that culminate in a question.",
    "It's a question that I've been meaning to ask a certain someone.",
    "When we come out of the university, I spot her right away.",
    "I've known Sylvie since we were kids. She's got a big heart and she's always been a good friend to me.",
    "But recently... I've felt that I want something more.",
    "More than just talking, more than just walking home together when our classes end.",
    "As soon as she catches my eye, I decide... qqq 75 yyy To ask her right away. nnn To ask her later.",
    "Hi there! How was class?",
    "Good...",
    "I can't bring myself to admit that it all went in one ear and out the other.",
    "Are you going home now? Wanna walk back with me?",
    "Sure!",
    "After a short while, we reach the meadows just outside the neighborhood where we both live.",
    "It's a scenic view I've grown used to. Autumn is especially beautiful here.",
    "When we were children, we played in these meadows a lot, so they're full of memories.",
    "Hey... Umm...",
    "She turns to me and smiles. She looks so welcoming that I feel my nervousness melt away.",
    "Ummm... Will you... ",
    "Will you be my artist for a visual novel?",
    "Silence.",
    "She looks so shocked that I begin to fear the worst. But then...",
    "Sure, but what is a \"Visual Novel?\" qqq It's a kind of videogame you can play on your computer or a console. yyy It's an interactive book. nnn It's a videogame.",
    "It's like an interactive book that you can read on a computer or a console.",
    "Interactive?",
    "You can make choices that lead to different events and endings in the story.",
    "So where does the 'visual' part come in?",
    "Visual novels have pictures and even music, sound effects, and sometimes voice acting to go along with the text.",
    "I see! That certainly sounds like fun. I actually used to make webcomics way back when, so I've got lots of story ideas.",
    "That's great! So...would you be interested in working with me as an artist?",
    "I'd love to!",
    " ggg 48",
    "",
    "",
    "It's a kind of videogame you can play on your computer or a console.",
    "Visual novels tell a story with pictures and music.",
    "Sometimes, you also get to make choices that affect the outcome of the story.",
    "So it's like those choose-your-adventure books?",
    "Exactly! I've got lots of different ideas that I think would work.",
    "And I thought maybe you could help me...since I know how you like to draw.",
    "It'd be hard for me to make a visual novel alone.",
    "Well, sure! I can try. I just hope I don't disappoint you.",
    "You know you could never disappoint me, Sylvie.",
    " ggg And so, we become a visual novel creating duo.",
    "",
    "",
    "And so, we become a visual novel creating duo.",
    "Over the years, we make lots of games and have a lot of fun making them.",
    "Our first game is based on one of Sylvie's ideas, but afterwards I get to come up with stories of my own, too.",
    "We take turns coming up with stories and characters and support each other to make some great games!",
    "And one day...",
    "Hey...",
    "Yes?",
    "Will you marry me?",
    "What? Where did this come from?",
    "Come on, how long have we been dating?",
    "A while...",
    "These last few years we've been making visual novels together, spending time together, helping each other...",
    "I've gotten to know you and care about you better than anyone else. And I think the same goes for you, right?",
    "Sylvie...",
    "But I know you're the indecisive type. If I held back, who knows when you'd propose?",
    "So will you marry me?",
    "Of course I will! I've actually been meaning to propose, honest!",
    "I know, I know.",
    "I guess... I was too worried about timing. I wanted to ask the right question at the right time.",
    "You worry too much. If only this were a visual novel and I could pick an option to give you more courage!",
    "We get married shortly after that.",
    "Our visual novel duo lives on even after we're married...and I try my best to be more decisive.",
    "Together, we live happily ever after even now.",
    "123quit123",
    "",
    "",
    "",
    "I can't get up the nerve to ask right now. With a gulp, I decide to ask her later.",
    "But I'm an indecisive person.",
    "I couldn't ask her that day and I end up never being able to ask her.",
    "I guess I'll never know the answer to my question now..."

}
return ScriptContainer